### ISSUE TITLE
Incorrect list of symbols in PHP

### ISSUE THREAD

**Issue by sebastien-gallet** [atom/language-php#118]
In PHP, if a function name first character is lowercased and the parameter is a strongly typed initialized array:
![screen shot 2016-01-17 at 10 59 52 am](https://cloud.githubusercontent.com/assets/968164/12375536/62d04934-bd0a-11e5-8be5-c0fafefcfaf4.png)

Then pressing the shortcut "Goto Symbol", the list of symbols shows the parameter name instead of the function name.
(As a side note, somehow it pick "name" in the comment as a symbol as well.) 
![screen shot 2016-01-17 at 11 00 00 am](https://cloud.githubusercontent.com/assets/968164/12375537/62d39d96-bd0a-11e5-8c15-6dc8ad518a15.png)

**Comment by tommyvdv** [comment]
I believe i'm having the same issue in this example and hope a few extra examples can help you pinpoint the source of the problem.

<img width="221" alt="1" src="https://cloud.githubusercontent.com/assets/83648/12554291/03d475f4-c37c-11e5-98ce-6e282573a888.png">
<img width="244" alt="2" src="https://cloud.githubusercontent.com/assets/83648/12554290/03c53b84-c37c-11e5-96c0-13398ecebb49.png">
<img width="242" alt="3" src="https://cloud.githubusercontent.com/assets/83648/12554289/03addebc-c37c-11e5-99b2-776791968c01.png">

The symbol definition for an optional parameter named `$locale` seems to override the method name.

In dense classes i'm also getting some hits on the code inside methods. This makes it hard to navigate some files. Disregard this if this behavior is intentional (I'm new to Atom and was a sublime user).

<img width="371" alt="4" src="https://cloud.githubusercontent.com/assets/83648/12554288/028c0dce-c37c-11e5-920d-94d65bab17d6.png">

**Comment by bj7** [comment]
I also experience an issue with the symbol list not being correct in PHP files. I have a function:
![image](https://cloud.githubusercontent.com/assets/1395096/15093554/ca055db4-1459-11e6-9924-274bba83471e.png)
When using Command-R (Mac) and searching on `view`, all I get back is the name of my class:
![image](https://cloud.githubusercontent.com/assets/1395096/15093561/ef4e53e6-1459-11e6-82e8-3a0c70c7a045.png)

Which file handles symbol list definitions? I would be glad to investigate.

**Comment by 50Wliu** [comment]
This issue was moved to atom/symbols-view#175

**Comment by 50Wliu** [comment]
Fairly certain that symbols-view handles this so I've moved the issue over there.
