### ISSUE TITLE
[PHPDoc] Highlight `@param` return types and variable names

### ISSUE THREAD

**Issue by Kroc** [atom/language-php#136]
The specification of PHPDoc types can be seen here:
https://phpdoc.org/docs/latest/references/phpdoc/types.html

I'm going to try take a stab at this, but I thought I'd file an issue so as to ask some basic questions.
1. Should I be editing 'php.cson' directly? -- is it being generated from somewhere else? It's a complete mess
2. What should I _not_ do? (to avoid getting a PR rejected)

**Comment by 50Wliu** [comment]
1.  Yes, you can edit it directly.  The reason it's so messy is because it's had to endure two filetype changes: first from xml to json, then from json to cson.
2.  Really as long as what you're adding works I'm very willing to work with you to get your PR merged :).  What you *should* definitely do though is add some specs to test the new highlighting additions!

**Comment by Kroc** [comment]
Great, thanks. Do you know what system Atom uses to understand the contents of the 'php.cson' file? I'd like to check what's possible with the schema.
