### ISSUE TITLE
Don't fallback to  'text.html.basic' if starting tag is not found

### ISSUE THREAD

**Issue by ludesign** [atom/language-php#182]
The reason is that packages that work with parts of a php file's code (ex. code peek) do not get syntax highlighting. 

A possible solutions for packages is to add `<?` and remove it in case the package writes the content back to the file.

Any other ideas?

**Comment by Ingramz** [comment]
if I understand correctly, code-peek creates a new temporary editor which only contains the specific function and applies the grammar of the whole document to highlight it. Code doesn't get highlighted because Atom expects PHP code to start with a start tag, which is part of a valid PHP document.

I know that Github had this issue with including PHP code in fenced code blocks some time ago, but I don't know what the solution was. The end result is that it is possible now to get such PHP snippets highlighted without having to add a start tag. As you can see here:
```php
function myFunc($a, $b) {
  return array_reverse(explode($a, $b));
}
```

We are probably looking for something that can force a document to start parse from a given context, eg `.source.php` and not the start context of the whole PHP grammar.

**Comment by ludesign** [comment]
Yes, that is correct. I like your suggestion and will spend some time with the grammar file next week. Initially the _hack_ I employed was to change the fallback but some contexts were messed up (ex. comments).

**Comment by 50Wliu** [comment]
Took a look at how hard this would be.  Here's my results with language-gfm, which previously was unable to highlight _any_ PHP code:

| Before | After |
| ------ | ----- |
| ![php-gfm-before](https://user-images.githubusercontent.com/2766036/27019404-4d5fa33a-4f06-11e7-9fad-4e88d326df5d.png) | ![php-gfm-after](https://user-images.githubusercontent.com/2766036/27019376-0c66e5b4-4f06-11e7-8569-a36d3ade5f71.png) |

PR hopefully tomorrow.
