### ISSUE TITLE
Closing ?> is scoped as source.php

### ISSUE THREAD

**Issue by chbk** [atom/language-php#286]
The `?` in `?>` is scoped as `source.php`. See [here](https://github.com/atom/language-php/blob/aa095129f29f4ffbf5db6f154aa283997ddbca29/grammars/php.cson#L85).

This leads to incorrect highlighting with syntax themes that highlight punctuation differently.

**Comment by Ingramz** [comment]
That is intentional.

If you have PHP code like `<?php |?>` and your cursor is the character `|`, then the idea is that the cursor would belong to the `.source.php` scope for snippets/autocomplete purposes.

To overcome the styling issue, apply the style of `.punctuation` also to `.punctuation .source`.

**Comment by chbk** [comment]
Alright, thanks for the clarification.
