### ISSUE TITLE
Cannot include php into another grammar package

### ISSUE THREAD

**Issue by mindpixel-labs** [atom/language-php#287]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

I am trying to support both HTML and PHP highlighting in my package/language grammar. Here is what my grammars.cson file looks like.
```
# Global Patterns
'patterns': [
  {
    'include': 'text.html.php'
  }
  {
    'include': '#components'
  }
]
```
The html highlighting works correctly when I include it, but not PHP. If I try to include other languages such as source.c or source.js it correctly imports their patterns and highlights the syntax, but PHP does not appear to be able to be included in another grammar files/packages.

### Versions
Atom    : 1.21.1
OS: Mac Sierra 10.12.5

**Comment by Ingramz** [comment]
It's not a PHP grammar issue, but an issue with the underlying grammar engine.

https://github.com/atom/first-mate/issues/40

**Comment by Ingramz** [comment]
If you want a working solution today, simply fork the PHP grammar and add your modifications on top of it. Just don't forget to occasionally pull in updates from this repository so that they wouldn't be too much out of sync. You can diff the PHP grammar and [Blade grammar](https://github.com/jawee/language-blade) to see how it's implemented there.

It's probably not the nicest solution, but it will have to do for now. You might also want to look into how it was solved in Textmate for the language you are trying to implement.

**Comment by 50Wliu** [comment]
Grouping this under #217, #182.

**Comment by mindpixel-labs** [comment]
@Ingramz Got it, thank you!
