### ISSUE TITLE
Arabic variable names not highlighted

### ISSUE THREAD

**Issue by roblourens** [atom/language-php#301]
```php
<?php

$abc = "a";
$سن = "a";

```

![image](https://user-images.githubusercontent.com/323878/33236402-343852f6-d207-11e7-879b-ac1baaa221c4.png)

This is legal in PHP apparently.

https://github.com/Microsoft/vscode/issues/34258

**Comment by jens1o** [comment]
This also affects German umlauts `[ÄÖÜ][äöü]` and the special char `ß`
![image](https://user-images.githubusercontent.com/11234139/33237888-ad99ec30-d280-11e7-8318-fdae96aaabb1.png)

**Comment by 50Wliu** [comment]
I won't be able to fix this until someone can give me a definitive regular expression that captures all valid PHP identifiers.  Because the [PHP manual](http://php.net/manual/en/language.variables.basics.php) says the following:
> Variable names follow the same rules as other labels in PHP. A valid variable name starts with a letter or underscore, followed by any number of letters, numbers, or underscores. As a regular expression, it would be expressed thus: `'[a-zA-Z_\x7f-\xff][a-zA-Z0-9_\x7f-\xff]*'`

The examples given in this issue are not covered under that regex.

**Comment by 50Wliu** [comment]
@jens1o I am unable to reproduce your issue with umlauts and ß.
![php-umlauts](https://user-images.githubusercontent.com/2766036/33280383-27989c44-d3a2-11e7-9a37-d6e39b71b49b.png)

**Comment by Ingramz** [comment]
The best I could find was a comment from a reputable PHP developer NikiC: https://stackoverflow.com/a/5358944

It does seem to check out that the Arabic characters above do have a byte sequence that can be matched by that regular expression. It likely fails in Atom because the matching is not done per byte but per utf-8 character.

Also it should be noted that Sublime Text uses`[[:alpha:]_][[:alnum:]_]*` possibly in unicode mode, which does seem to work around it to some extent, but I am guessing it matches some characters that are illegal in PHP and misses some, similarly to this issue.

**Comment by jens1o** [comment]
@50Wliu Okay, with todays insiders build it is working fine again... Don't ask me why it didn't yesterday, I don't know.

I think this issue can be closed now.
