### ISSUE TITLE
Wrong coloring under php

### ISSUE THREAD

**Issue by sanada01** [atom/language-php#345]
### Description

It often spoils the color of long lines.

[sample.txt](https://github.com/atom/atom/files/2623666/sample.txt)

### Steps to Reproduce

1. Open sample.txt and change file format to php
2. Wrong coloring on line four end

**Expected behavior:** Correct coloring

**Actual behavior:** Wrong coloring

**Reproduces how often:** 100%

### Versions

Atom    : 1.32.2
Electron: 2.0.9
Chrome  : 61.0.3163.100
Node    : 8.9.3

apm  2.1.2
npm  6.2.0
node 8.9.3 x64
atom 1.32.2
python
git 2.11.0.windows.1
visual studio

**Comment by Ingramz** [comment]
I think it is another case of hitting the token render limit of editor. The file is actually parsed correctly, just that after a number of tokens the rest of the line is styled by the last processed token. https://github.com/atom/atom/issues/1667

**Comment by thomasjo** [comment]
@Ingramz Yeah, you're totally correct. Thanks!

@sanada01 Looks like you're hitting the problem with token limits in the old first-mate grammars, which you can read more about in https://github.com/atom/atom/issues/1667. The good news is that the introduction of the new Tree-sitter grammars resolves this problem; see https://github.com/atom/atom/issues/1667#issuecomment-439151902.

Unfortunately this package does not yet have a Tree-sitter grammar, but work has started and you can track the progress in #303. You might want to sign up for updates there.

Because this issue will be resolved once #303 is merged, I'm going to close this issue.
Thanks again for your report!

**Comment by sanada01** [comment]
> @Ingramz Yeah, you're totally correct. Thanks!
> 
> @sanada01 Looks like you're hitting the problem with token limits in the old first-mate grammars, which you can read more about in [atom/atom#1667](https://github.com/atom/atom/issues/1667). The good news is that the introduction of the new Tree-sitter grammars resolves this problem; see [atom/atom#1667 (comment)](https://github.com/atom/atom/issues/1667#issuecomment-439151902).
> 
> Unfortunately this package does not yet have a Tree-sitter grammar, but work has started and you can track the progress in #303. You might want to sign up for updates there.
> 
> Because this issue will be resolved once #303 is merged, I'm going to close this issue.
> Thanks again for your report!

Thanks! :)
