### ISSUE TITLE
Tokenization is broken after solr syntax

### ISSUE THREAD

**Issue by alexr00** [atom/language-php#374]
From @aksineDby in https://github.com/microsoft/vscode/issues/85525

![Снимок экрана от 2019-11-25 11-45-03](https://user-images.githubusercontent.com/34752422/69525443-2d148380-0f79-11ea-8022-fd1cb16aea3f.png)
code line:
$query .= " AND date:[" . $data['date'] . " TO " . $data['date'] . "] ";

All after " AND date:[" has the wrong color scheme

```php
<?php
$query .= " AND date:[" . $data['date'] . " TO " . $data['date'] . "] ";
$json['criterion'] += array(
	'title' =>wfMessage('meeting_date')->text()
);
```

**Comment by lkashef** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀
