### ISSUE TITLE
Syntax Highlighting of Closure Variable Inconsistent

### ISSUE THREAD

**Issue by JacksonKearl** [atom/language-php#382]
From https://github.com/microsoft/vscode/issues/90832:

Steps to Reproduce:

1. Set Color Theme to e.g. Dark+
1. Define a function closure and assign it to a variable
1. Call the closure
1. The `$` is inconsistently colored

```php
<?php

class Test
{
    public function test()
    {
        $callback = function() {};

        $callback;      // Consistent coloring
        $callback();    // Inconsistent coloring
    }
}
```

Dark+ Color Theme (Inconsistent)
![image](https://user-images.githubusercontent.com/13063023/74665584-49067a80-51a0-11ea-83d0-715762e9ac03.png)

**Comment by PythooonUser** [comment]
@KapitanOczywisty Just a question about the general procedure for this project here: I see there is a working PR ready for this issue, but it has not yet been merged. I understand this issue is not a prioritized one, still wondering about the process here.

**Comment by KapitanOczywisty** [comment]
@PythooonUser AFIK Atom had peak in popularity, then other editors took it's place, and now it's treated as spear parts for projects like vscode. Atom team has other priorities than working on packages, and vscode team cannot merge anything here. This is not "ideal" situation, because there is no other way to update php syntax higligting in vscode, but what can we do..

I might be working on updates for php8 shortly and then I'll nag somebody personally to take a look at PRs.

**Comment by PythooonUser** [comment]
Okay, understand. Yeah, that's not an ideal situation, indeed. But I'm glad you are working on this :)
