### ISSUE TITLE
MySQL syntax highlight stops working when including an array with closing/opening quotation

### ISSUE THREAD

**Issue by Kaperstone** [atom/language-php#52]
When you close with a quatation in the middle of the query, the MySQL syntax highlight stops working.

A screenshot -
![img_17102014_121914](https://cloud.githubusercontent.com/assets/8384463/5463316/390faaf4-8584-11e4-8359-c76d6899c230.png)

**Comment by frozzare** [comment]
@kevinsawicki isn't the problem that it's to few keywords here https://github.com/atom/language-php/blob/f8b4f9a188954f8eda3931a969a88d407d595794/grammars/php.cson#L1477?

**Comment by andre-koch** [comment]
Please add FROM, WHERE, LEFT JOIN, RIGHT JOIN, JOIN and also please include the syntax highlight if there is a space before the keyword; just like how AND works. This is really useful when creating queries based on options switched on via functions to add or remove certain parts of the query to improve speed on calls where additional joining is not required.

**Comment by grithin** [comment]
File syntax highlighting still breaks for various concatenated strings.  Since this has been the case for years now, and since I don't care for the highlighting, here is the method for simply removing this broken sql inline highlighting on linux:

extract ~/.atom/.apm/language-php/0.26.0/package.tgz
edit grammars/php.cson
remove keys : 'sql-string-single-quoted' , 'sql-string-double-quoted'
repackage and replace package.tgz
reload window
