### ISSUE TITLE
Array closing parenthesis highlighted incorrectly

### ISSUE THREAD

**Issue by vojtagrec** [atom/language-php#60]
The closing parenthesis in an `array()` statement (= the one having `class="punctuation definition array end php"`) seems to be selected incorrectly – simply the first `)` character is selected, which is not correct if there is a function/method called inside the `array()` definition. See the screenshot:

![image](https://cloud.githubusercontent.com/assets/170892/6079590/a8da3a4c-ae07-11e4-9bfe-ad5de1685146.png)

It is using Seti syntax theme which assigns the `array()` parentheses a different colour (light blue in this case).

_Atom 0.177.0 on Mac OS X 10.10.2_

**Comment by zr9** [comment]
I'm can add fix for single line, but multiline now not possible due to grammar limits looks please issue #87 for details. For single line is possible. @50Wliu That way it be ok?

**Comment by 50Wliu** [comment]
@zr9 could you try changing the array regex to a `begin`/`end` match instead of a `match`?  begin/end can match multiple lines.

**Comment by Ingramz** [comment]
@50Wliu `end` will stop at the first occurrence of the pattern you are looking for.

If we take the image above as an example - if you were looking for `)`, it would stop on the second line at `Is Artist?')` and rest of it will be captured by some other rule. By looking at the coloring of the parentheses, I think this is exactly what it is doing already.

Since you can only match a single line at a time, then the best case would be that we'd be stopping at the last occurrence of closing parentheses of that line. That wouldn't solve the issue with multiple lines.

To balance parentheses, we'd need a stack in order to keep track of the state. That we simply cannot do with these grammars.

**Comment by 50Wliu** [comment]
@Ingramz no, you can capture parentheses within the match, eg:
```coffee
'begin': 'array\\('
'end': '\\)'
'patterns': [
  {
    'begin': '\\('
    'end': '\\)'
    'patterns': [
      {
        'include': '#self'
      }
    ]
  }
]
```

language-javascript, c, and I believe some others match brackets this way.

**Comment by zr9** [comment]
@50Wliu Yup could be, need to test, because it hard to say how grammar work inside, not a much docs available, is grammar in that case works like recursive regex then it will work, otherwise there is possible probably another way with capturing array content in begin(with recursion as well), i'm try and get back to you in a few hours

**Comment by Ingramz** [comment]
@50Wliu took a look at one of my older grammars and found out that I've even used that kind of construct. Thanks for the reminder, this definitely gave me some ideas.

But in the context of PHP, that's quite a bit of work to get all the constructs matching that way correctly.

**Comment by zr9** [comment]
@Ingramz Could you give me some more info on that construction, is it supposed to work as recursion? Because now i'm trying to use it, and so far had 0 luck in that

**Comment by Ingramz** [comment]
@zr9 yes, it should be recursive. Try `$self` instead of `#self`.

**Comment by zr9** [comment]
@50Wliu @Ingramz Okay bad news and good news, bad first.

1) The rule above is not exactly recursive it kind of include scope which in patterns
2) There is some bug in grammar parser or in itself grammar(not yet know)

Good news :)

![array_issue](https://cloud.githubusercontent.com/assets/13107923/12428087/ca5a19d2-bef3-11e5-8261-909769b7158d.png)

That rule inside patterns is can skip some scopes inside of itself it they kind of busy(based on tests, any docs on that are welcome). So it possible, but there problems, i'm still not getting logic behind grammar, in which cases it targeting and in which not. For bug i'm give more info once i'm get it at least little clear

**Comment by zr9** [comment]
Yup grammar bug, not logic bug, and for rule 1, it works only when scope is get busy with included pattern, then it skip that one since it busy and match next one, that info is from observations and test so can be not 100% true. Itself whole thing is possible but require issue #47 to be done in prior, and probably serious rules update, since parentheses need not only in global space but as well in many other scopes

**Comment by 50Wliu** [comment]
Closing in favor of #47.
